### ISSUE TITLE
リモートリポジトリの管理ツールから記録ツールを起動してテストを開始すると、空のテスト結果が残る

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#111]
## Describe the bug

リモートリポジトリの管理ツールから記録ツールを起動してテストを開始すると、空のテスト結果が残る。

また、記録を再開する場合も同様に、再開前のテスト結果が残ってしまう。

## To reproduce

リモートリポジトリの管理ツールから記録ツールを起動してテストを行い、テスト結果をリモートリポジトリに登録する。
もしくは、リモートリポジトリに接続し、既存のセッションを再開してテストを行い、テスト結果をリモートリポジトリに登録する

## Expected behavior

記録開始時にセッションと紐付いていたテスト結果が残らない

**Comment by fujiwr** [comment]
アーキテクチャが変わり、リモートにアップロードする方式ではなくなったためクローズ。
