### ISSUE TITLE
Macにおいて設定ファイルからポートを変更すると起動スクリプトでツールが起動できない

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#112]
## Describe the bug

Macにおいて設定ファイルからポートを変更すると、起動スクリプト実行時に repository に接続できずツールが起動できない

## To reproduce

Mac版起動スクリプトでポートを変更してから起動する

## Expected behavior

Win版と同様に起動できる

**Comment by masaki-tajima** [comment]
issue整理のためクローズとする。
