### ISSUE TITLE
管理ツールから起票状態を変更できるようにする

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#113]
管理ツールから起票状態を変更できないため、レビュー時に不便である。

管理ツールでの編集の制限をなくすことも検討する。

**Comment by ndsuzuki** [comment]
@knukio さん   
本件ですが、既存利用者含め、展開に向けて重要機能と認識しており対応時期の目途が分かれば連携いただけないでしょうか？

**Comment by knukio** [comment]
@ndsuzuki 3月中に対応してリリースしたいと考えています。

**Comment by ndsuzuki** [comment]
@knukio さん
回答ありがとうございます。承知しました。

**Comment by knukio** [comment]
暫定的に管理ツールのレビュー画面の操作一覧から右クリックで目的・気づきを編集できるようにしました。
タグで `reported` を入れると起票済み、 `invalid` を入れると起票なしになります。

暫定対処のため、現状以下のような問題がありますが、起票状態の変更のみをする場合は問題ないと思います。
- #118 
- #119
- #120
