### ISSUE TITLE
レビュー画面の操作一覧から目的・気づきを削除できるようにする

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#119]
**Is your feature request related to a problem? Please describe.**

シーケンス図のみからしか目的・気づきを削除できないのは不自然

**Describe the solution you'd like**

操作一覧からも目的・気づきを削除できるようにする。
右クリックコンテキストメニューに削除機能を追加する。

**Comment by masaki-tajima** [comment]
複数の事業会社から要望が上がっているため優先度を上げる．
