### ISSUE TITLE
管理ツールのレビュー画面において操作履歴の再生を止める方法がない

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#120]
**Describe the bug**

管理ツールのレビュー画面において操作履歴の再生を止める方法がなく、ブラウザを閉じて止めると少し遅れて「履歴の再生を終了した」ダイアログが出る。

**To Reproduce**

管理ツールのレビュー画面の操作一覧を右クリックし、履歴の再生を行う。
ブラウザが立ち上がって操作の再生ができるが、止める方法がない。

**Expected behavior**

記録ツールと同様に停止機能をつける。
もしくは、ブラウザを閉じることで正常に停止するようにする。

**Comment by fujiwr** [comment]
管理ツールのレビュー画面から操作の再生はできなくなったため、クローズとする。
