### ISSUE TITLE
生成テストスクリプトでテストケース毎にブラウザの終了処理を入れられるようにする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#123]
**Is your feature request related to a problem? Please describe.**
生成したテストスクリプトのtest.spec.jsについて、afterEachメソッドによるブラウザの終了処理を追加してほしい。
テストデータを用いて同一シナリオを繰り返し実行する際、前回実行時の情報がセッションで保持されエラーとなるケースがあった。

# 対処
driverを使い回すかどうかをオプションで変えられるようにすれば解決？
* 当該事象解消のために「Webdriverの再起動処理をafterEachメソッドに追加する」というオプションを、テストスクリプト生成時に指定できるようにしたい。
* テストスクリプト生成時に指定させる文言としては「テストケースごとにブラウザを再起動する」等のユーザが分かりやすい文言にする。

**Comment by s151013** [comment]
当該事象解消のために「Webdriverの再起動処理をafterEachメソッドに追加する」 というオプションを、テストスクリプト生成時に指定できるようにしたい。

とスクリプト生成時に指定させる文言としては「テストケースごとにブラウザを再起動する」等のユーザが分かりやすい文言にする。

**Comment by masaki-tajima** [comment]
テストスクリプトは編集することを想定しており，手動で処理を記述していただく運用対処としたい，クローズとする．
