### ISSUE TITLE
画面遷移図にて画面遷移契機のエッジ文字列にマウスカーソルを合わせると赤太文字になるがそれに伴って文字の右端が切れる

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#124]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
特段，見栄えに致命的な影響は無いとみられる．
issue整理のためクローズとする．
