### ISSUE TITLE
スナップショット上のストーリー画面で添付された画像をクリックすると画面遷移してしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#125]
**Describe the bug**

**To Reproduce**

**Expected behavior**
本体側の挙動だと、画面遷移せずにホップアップで表示する。スナップショット側でも同様の表示方法にする。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.10.0で確認したところ，新規タブでブラウザ上で開かれる仕様であった．
特段，問題は発生しないため，クローズとする．
