### ISSUE TITLE
ポートが競合している場合何が起きているかユーザに分かりにくい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#127]
ポートが競合している場合何が起きているかユーザに分かりにくい。
今回3002番ポートが他のアプリと競合しており、LatteArtの3002番を使うAPIでおそらくエラーが起こってると思われます(コンソールには何もエラーは表示されません)。
その際に3000, 3001番ポートのアプリは無事でLatteArtはブラウザから起動されるのですが、エラーダイアログが画面上に表示されて、そのダイアログはエラーアイコンだけがありタイトルも内容もない真っ白なダイアログとして表示されてしまうため、ユーザは何が起きたか理解する事が出来ません。
（ブラウザのコンソールエラーを見ると3002ポートのAPIに関するエラーが発生しているのでそこから察する事は可能です。）

**Comment by masaki-tajima** [comment]
最新のv2.2.1でも挙動が改善されていないか？確認要

**Comment by masaki-tajima** [comment]
v2.4.0では，コンソールに
`Error: listen EADDRINUSE: address already in use :::3306`
との表示あり．ポートが既に使われていることが読み取れ，ブラウザが起動しない．
改善されたとみなしてクローズとする．
