### ISSUE TITLE
生成テストスクリプトについて、テストケースを分割せず、単一ケースとして出力する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#128]
## 完了条件
単一ケースをしても出力可能なオプションを付与する、等

## 要望
生成テストスクリプトについて、テストケースを分割せず、単一ケースとして出力する、または終了操作をテストケース毎に付与するような仕組みがほしい。

## 参考
※「ログイン→処理A→処理B→ログアウト」の操作をすると「ログイン→処理A」「ログイン→処理B→ログアウト」に分割されるが、対象システムでは前者はログアウトしていないため、2重ログインと判定されエラーとなる。
↓
特定の環境に特化した仕様にすると他の環境で不都合が起きる可能性があるため，検討が必要だが
純粋にリプレイするスクリプトをPOを利用して生成することで対応できるかもしれない。
その後、複数の要望があったため、
「テストケースを分割せず、単一ケースとして出力する」についてはオプション機能として要望する。

**Comment by fujiwr** [comment]
操作そのままの生成に対応したためクローズ。
