### ISSUE TITLE
記録ツールにてダイアログ(confirm,alart,dialog等)上の操作が記録されない

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#13]
**Describe the bug**
記録対象としてダイアログ(confirm,alart,dialog等)で実行した操作が記録できない  

**Expected behavior**
ダイアログ上での操作も記録対象となる  

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome v96]
 - Version [1.7.5]

**Additional context**
要件バグ一覧表No.138からの転記

**Comment by masaki-tajima** [comment]
ダイアログ上の操作の記録は、「動画による記録」で操作の様子の記録に対応しました。
操作履歴への操作の記録は対応していませんが、対応の見込みが無く、issue整理のためクローズとします。
