### ISSUE TITLE
テストスクリプト生成において、テストデータにデフォルト値を含めるようにする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#131]
うまく行かない例: seleniumサンプルサイト等
```
テストスクリプト生成機能について、以下画面操作を記録した場合、テストスクリプトが正常終了しない。
■例
画面A：入力画面（必須入力項目が複数存在）
画面B：エラー画面
画面C：正常画面
■操作
画面A（必須入力項目の一部のみ入力）→画面B→画面A（残りの必須項目を入力）→画面C
■テストスクリプトのシナリオ
①画面A→画面B
②画面A→画面C
※②の入力データが（残りの必須項目を入力）のみとなるため、画面Bへ遷移する
```
DONE条件:
テスターが操作していなくても画面にデフォルト値が入っていればそれを入力する操作をメソッドに加える
検討事項:

- どの要素をデフォルト入力として含めるかが自明ではない。
  - 空文字でないかつ過去に操作されたことがある入力フォームがあれば操作に含める？
- この処理を入れることでうまくいかなくなる場合がありそう。

**Comment by masaki-tajima** [comment]
テストスクリプト生成機能は，あくまで「雛形」であり，編集されて活用されることを想定している．
懸念事項にも挙げられているように，一律にこの処理により，弊害が発生する懸念がある．
issue整理のため一旦クローズとし，今後必要に応じて特定事象が発生した場合に再検討することとする．
