### ISSUE TITLE
特定サイトでテスト中、特定の要素をクリックすると画面に暗幕がかかる

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#133]
下記３か所で確認（同様の原因かは未確認）

- google検索画面右上のハンバーガーメニュー（？）をクリック
- 下記URLの車の画像より下の部分をクリック
https://www3.nissan.co.jp/vehicles/new/x-trail.html?scadid=AD_TIJ_XT_YJ_YDNR_PC_00484701&yclid=YJAD.1612744552.w6LOz6Wdcq29G53Rn81rQ52W5is3FLJuQnApHffstbA5rLlcYm4f0ekjeDGTd9vNaX1H9xrlF7ui8SONv.PjVDZRrcFWHemOwCIWCmoA1SORrw8-
- 下記URLの下の方クリック
https://www.msn.com/ja-jp
- 下記URLの任意のフォームをクリックし，入力しようとする
https://www.kuroutoshikou.com/contact/kurouto-mailsupport.html

**Comment by masaki-tajima** [comment]
v2.10.0，Windows，Chromeにて確認したところ，以下で再現確認．
- google検索画面右上のハンバーガーメニュー（・が9点あるボタン）
- 任意のフォーム
  - https://www.kuroutoshikou.com/contact/kurouto-mailsupport.html

※msnサイトについては暗幕ではなく画面遷移を確認できなかったため， #804 として起票

**Comment by fujiwr** [comment]
> 以下サイトのお問い合わせ欄にあるフォーム

iframe内をクリックしたことにより、親フレームからblurされ、暗幕がかかってしまっている。

**Comment by fujiwr** [comment]
以下の操作手順でユーザに記録対象のフレームを指定させる形で対応する。

1. 記録ツールで記録中、フッタのボタンからフレームを選択するダイアログを開く。
2. ダイアログ上で記録対象フレーム選択して切り替える。
