### ISSUE TITLE
キャプチャー時にかかる暗幕が全画面にかからない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#134]
window選択ボックス表示時や、他タブで操作を行っているときにかかる暗幕が全画面にかからない（メニューより上部がむき出しのままとなっている）。
下記ページで確認

https://www.ntt-tx.co.jp/column/

**Comment by masaki-tajima** [comment]
全画面にかけることは必須ではなく，ユーザーにLatteArt処理中の待機を促すための補助的表示である．
運用対処可能とみられ，本件クローズとする．
