### ISSUE TITLE
複数のセッションをマージしてレビューできるようにする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#136]
- 管理ツールのストーリー画面で、レビュー対象セッションを複数選択可能とする。
- 複数選択した上でレビュー画面に移動した場合、以下のように複数のテスト結果をマージしてレビュー画面に表示する。
  - シーケンス図
    - 図はマージせず、それぞれのテスト結果のシーケンス図を切り替えて表示できるようにする(従来の画面遷移図のように選択肢を選んで表示するイメージ)
  - 画面遷移図、画面部品カバレッジ
    - レビュー対象の全てのテスト結果をマージして表示する。

**Comment by fujiwr** [comment]
- ストーリー画面の「レビューする」ボタンをプルダウンリストの上に配置する(レビュー対象を選択中にボタンが見えなくなるため)。
- レビュー対象プルダウンリストで、表示される文言を「セッションN (テスト結果名)」の形に修正する。
- レビュー対象プルダウンリストで、表示される文言がプルダウンリストからはみ出る場合は末尾を「...」とする（フルHDで表示が崩れないこと）
