### ISSUE TITLE
キャプチャーツールでテスト結果名を修正した後直接リセットボタンを押下するとテスト結果名がクリアされていない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#139]
1. テスト結果名をAにする
1. キャプチャーする
1. キャプチャー終了する
1. テスト結果名をBにする
1. リセットする

上記の後、リセットボタンを押下したので、最終的にテスト結果名は空になっているべきだが、なっていない。

**Comment by masaki-tajima** [comment]
v2.14.2ではリセットボタン廃止済み。クローズとする。
