### ISSUE TITLE
最初の目的がたてづらいため、テスト開始時に目的を入れるのではなく、記録を開始してから目的を入力できるようになるとよい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#141]
テストをする際、画面を見てからどこの画面項目のテストをするか決めるため、最初に目的を入れる際には明確に目的を入力できず、画面を見て再度目的を入力しなおす必要があり、最初の目的入力の意味がなくなるため、記録開始してから最初の目的を入力できるようになると良いかも。

**Comment by masaki-tajima** [comment]
#586 にも関連する．
目的の範囲指定が無いために，開始時には「意味のない目的」を入力しなければならないケースが考えられる．

**Comment by masaki-tajima** [comment]
#623 で対応することとし、クローズとする。
