### ISSUE TITLE
テストマトリクス名に半角英数で文字数が多い入力だと改行されず、突き抜けてしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#144]
テストマトリクス名に半角英数で文字数を多く入力し、ブラウザサイズを小さくして確認すると文字がボタンの裏に突き抜けている
※全角文字の場合は改行されている。

**Comment by masaki-tajima** [comment]
半角英数が連続で入力されるケースは少なく、英単語の場合は半角スペース等が加わるとみられる。
また、本件はブラウザサイズを小さくした場合にのみ発生する。
issue整理のためクローズとする。
