### ISSUE TITLE
メモ一覧ダイアログで概要が突き抜けてしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#145]
**Describe the bug**
Noteの概要を長文(半角英数)にした場合、メモ一覧ダイアログの概要表示欄が長くなってしまう（横スクロールが発生してしまう）
他のところ同様、ある程度の文字数で省略するか、改行するようにした方が良いかも

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0で確認したところ，改行されて，横スクロールは発生しなかった．クローズとする．
