### ISSUE TITLE
記録の一時停止中に画面遷移した際、操作履歴に表示されるグレーのscreentransitionの行の罫線が途中で消えている

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#146]
記録の一時停止中に画面遷移した際、操作履歴に表示されるグレーのscreentransitionの行の罫線が途中で消えている。

期待結果
罫線が消えていないこと。

**Comment by masaki-tajima** [comment]
本件，罫線の色と行の背景色が同じ色のため，罫線が消えているように見えるのではないかと想定する．
致命的でないためbugを外す．

**Comment by masaki-tajima** [comment]
ユーザ影響が少なく，issue整理のためクローズとする．
