### ISSUE TITLE
設定画面の優先条件の定義にて、有効な定義の定義名を更新したあと同一定義内の他の入力要素をクリックするとフォーカスが勝手にはずれる

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#147]
設定画面の画面遷移の定義にて、定義名を更新したあと同一定義内の詳細定義の「URL 等のプルダウンリスト」「設定文言」「文字列が含まれている等のプルダウンリスト」のいずれかをクリックすると、クリックした入力フォームのフォーカスが勝手に外れる。

別の定義の入力欄をクリックしてもフォーカスは外れない
おそらく時間差で更新時のバックエンドで処理された結果が返ってきて、そのタイミングでフォーカスが外れたと思われる

**Comment by masaki-tajima** [comment]
ユーザ影響が少なく，issue整理のためクローズとする．
