### ISSUE TITLE
起動スクリプトの終了時にサーバクローズのログがない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#148]
**Describe the bug**
現状おそらくサーバ終了ごとのタイミングで「^C」がコマンドプロンプト上に表示されているが、代わりに例えば「CLOSE latteart-repository」などが表示されていると良い。

**To Reproduce**

**Expected behavior**
* 起動スクリプト終了時のサーバクローズ毎に「CLOSE latteart-repository」等のメッセージが表示されること。
* 「^C」が表示されないこと。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
サーバ終了のログが出た場合でもプロンプト画面はすぐに閉じられることとなり，影響が少ないためissue整理のためクローズとする．
