### ISSUE TITLE
履歴画面の操作履歴一覧についてアップダウンキーによる操作を可能としてほしい

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#15]
**Is your feature request related to a problem? Please describe.**
履歴画面の操作履歴一覧については、マウスで逐一クリックして該当操作を確認する必要があるが、1セッションで表示される操作が大量となるため、マウス操作ではレビュー効率が落ちてしまう。  

**Describe the solution you'd like**
操作履歴一覧でアップダウンキーによる操作を可能することで短時間かつ簡単に実施内容を確認でき、レビューの効率化につながると思われる。  

**Additional context**
要件バグ一覧表No.71からの転記

**Comment by knukio** [comment]
#26 と同じ
v2.2.0 で対応
