### ISSUE TITLE
ストーリー画面にて、セッションのテスト中の気づきの「起票状態」欄の意図がわかりづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#150]
**Is your feature request related to a problem? Please describe.**
例えば「未選択」等のほうがよいと思われる。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
現状，当該項目は，気づきに「reported」タグを付与した場合に「起票済み」，
付与していない場合に「起票状態」と表示される．

この「起票状態」の意図がユーザーにとってわかりづらく，またreportedタグと連動していることもドキュメントに明記されていない．
当該項目の本来の目的は，他のBTSとLatteArt上に登録した「気づき」を手動で連携する際の補助的機能として活用されることが目的だった．
その本来の目的に即し，以下対処としたい．

## 対処方針
- 「未起票」「起票済」の2パターンの表示とする
- 当該項目をクリックしたとき，上記パターンを変更できる（すなわち，レビュー画面や記録ツールから気づきを変更せずに，このストーリー画面から直接reportedタグを当該項目のクリック操作により変更できるものとする）
  - 変更すると，気づきの「reported」タグ属性が追加，もしくは削除される

**Comment by fujiwr** [comment]
- セッションの「テスト目的・気づき」欄で、各気づき下部を起票状態ではなく、タグのチップを並べる形にする。
- 気づきの「詳細」ボタン押下で開かれるダイアログ上で、タグを編集可能にする(起票状態欄は削除する)。
  - 詳細ボタンからタグの変更ができる旨(BTSとの手動連携に活用できる点)をドキュメントに記載する。

**Comment by nemotoaa** [comment]
追加対応
- 「起票」を「検出」に変更
- 品質管理画面で「バグ＝bugタグを付与した気づき」である旨を表示（単位の場所に記載？）
- reportedタグはプリセットの選択肢に残す。
- プリセットのタグの説明をドキュメントに追記する。以下の内容を記載。
	- bug
	完了になったセッション内に bug タグがついた気づきが存在する場合、ストーリーの摘出バグ数が加算されます。
	- reported
	LatteArtの他機能では利用されないため、単純なマーカーとして使用できます。BTS等のLatteArt外のシステムでバグを管理する際に、外部システム側に起票済みである旨を示すために使用すると便利です。
