### ISSUE TITLE
プリセットの観点（テスト目的候補）を用意しておいて、選択できるようにしておくと目的を立てやすいのではないか

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#151]
**Is your feature request related to a problem? Please describe.**
プリセットの観点（テスト目的候補）を用意しておいて、選択できるようにしておくと、探索的テストに慣れていないテスターでもテスト目的を起こしやすいのではないか。
- 例：
  - 遷移先が正しいのか
  - 文字数が正しいのか
  - 空文字なのか
  - など

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
探索的テストの範囲を狭めてしまう要因にもつながるため、本件は悩ましい。
ただし、過去のテスト活動データを活用するという点では、本提案は有用な機能につながる可能性のある意見である。

**Comment by masaki-tajima** [comment]
v2.15.2現在ではテストヒント機能によるテスト設計支援の拡張を行い、また拡張機能によってさらに高度な開発も進められているため、本件クローズとする。
