### ISSUE TITLE
表示文言での画面定義設定を行う際、非表示の要素配下に文言が含まれる場合も該当してしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#152]
非表示の表示文言配下にある要素は、ユーザとしては視認できないため画面定義設定での表示文言としては含めるべきではないが、`display:none`等で非表示になっているだけの要素はヒットしてしまう。

**Comment by masaki-tajima** [comment]
v2.10.0で以下サイトに対し確認したが，再現しないため，クローズとする．
https://www.wabiapp.com/WabiSampleSource/html5/sample/contents_change_disp_none.html
