### ISSUE TITLE
画面遷移図下部の入力値一覧で、直接操作していなくて間接的に値が変わる入力要素がデフォルト値として認識されてしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fujiwr** [comment]
仕様通りのためクローズ
