### ISSUE TITLE
記録時にLatteArtの赤枠等のdivの増減が影響してxpathがずれる場合がある

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**
- 案
  - divを使わないようにする
  - 別の階層におくようにする(absolute等で指定)
  - cssで直接赤枠を指定するようにする

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fujiwr** [comment]
対処済みのためクローズ
