### ISSUE TITLE
「テスト計画」「テスト対象」「ストーリー」『〇〇フロー」「テスト」等の単語の意味と関係性、役割が分かりづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#159]
**Is your feature request related to a problem? Please describe.**
「テスト計画」「テスト対象」「ストーリー」『〇〇フロー」「テスト」等の単語の意味と関係性、役割が分かりづらいため、実務で想定されるシナリオに沿った使い方のチュートリアルドキュメントがあるとイメージしやすいのではないか。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
ドキュメントに記載があり、また管理ツールのテストマトリクスの用語の説明には「？」マークをオーバーマウスした際に説明が表示されるものとなっている。
現状、問題は無いと考え、issue整理のためクローズとする。
