### ISSUE TITLE
ボタンを押下してから時間差で画面構成を動的に構築するようなサイトの場合、適切なタイミングで画面キャプチャを取得できない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#160]
**Is your feature request related to a problem? Please describe.**
自動画面キャプチャの他に任意のタイミングで画面キャプチャをとれるようにして、直前の操作に紐づけられるようにするのはどうか。
→１操作に対して複数画面キャプチャが紐づくイメージ
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
クリックのたびにスクリーンショットを取得でき，また気づき投入時にもスクリーンショットを別途記録できるため，本件の要件を満たしている．よってクローズとする．
