### ISSUE TITLE
リプレイ機能でエラーが発生したとき、操作一覧上のどの操作で止まったのか後から見ることができない。

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#162]
**Is your feature request related to a problem? Please describe.**
リプレイに連動して、操作一覧の行の色がかわっていくとよい。（今操作されている行がハイライトするなど）

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
#276 に集約する．クローズとする．
