### ISSUE TITLE
テストスクリプトを生成し、ダウンロードダイアログを閉じたタイミングでファイルを削除するようにする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#163]
**Is your feature request related to a problem? Please describe.**
ダウンロード中に問題が発生する可能性があるため、削除前に警告メッセージも併せてだすほうがよい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knukio** [comment]
ダウンロード完了のタイミングを把握できないため、この処理は行わない。
