### ISSUE TITLE
画面定義設定で一度画面をまとめた後、再度設定を変えたいときに元のURLやタイトルが見えないため設定しづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
元のURLやタイトルは，設定画面から画面定義の無効化を一時的に行えば確認が可能．
issue整理のためクローズとする．
