### ISSUE TITLE
シーケンス図や画面遷移図上で画面名を変更できるとよい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#167]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
ブラウザウィンドウを２つ表示することで，設定画面とシーケンス図の同時表示が可能である．
運用対処可能なため，issue整理のためクローズとする．
