### ISSUE TITLE
セッションごとに設定が保存されているとよい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#168]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0では，ツール上の変更の保存はリアルタイムに行われる．
どの設定を指しているか不明ではあるが，古い時期に起票されたものであるため，解決されているとみなし，一旦クローズとする．
