### ISSUE TITLE
シーケンス図の表示改善

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#170]
操作一覧を可視化しているシーケンス図の表示をより見やすい形に改善する。

### 案

目的やウィンドウなどの枠が多く、また図が長くなったときに見づらくなるため、複数の図に分ける。
※以下のようなイメージでテスト目的の流れを最初にフローチャートで示し、そのあとテスト目的ごとにシーケンス図を作るのはどうか。
![image](https://user-images.githubusercontent.com/9267473/160564437-7d246c20-a6b4-41c8-8241-7c679b0d2425.png)

**Comment by fujiwr** [comment]
「テストの流れ」の部分は図ではなくセレクトボックスで実装することとする。

**Comment by fujiwr** [comment]
テスト目的を編集するボタンの名称を「テスト目的の編集」にする。
また、テスト目的を削除するボタンを削除する。
