### ISSUE TITLE
画面遷移直後すぐにブラウザバックした場合、その画面の入力値情報が入力値一覧に表示されない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#173]
**Describe the bug**
あるべき動作の検討から実施する必要がある。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
基本的にはユーザーが手動操作により入力を行ったものを入力値一覧に表示するべきだが，
本件は「画面遷移直後すぐにブラウザバックした場合」であり，手動での入力行為を行っておらず，
デフォルトで入力済みのINPUT要素等が入力値一覧に表示されない事象を示している．

操作を何等か行った場合には入力値一覧に表示されるため，運用上はこちらが想定されている．
想定されないケースとして，クローズとする．
