### ISSUE TITLE
ストーリー画面右上のレビュー対象セッションの選択時、importしたテスト結果の名称が表示されているとわかりやすい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#180]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.12.0ではレビュー対象セッションの選択ダイアログにテスト結果名が表示されるためクローズとする．
