### ISSUE TITLE
Projectデータの更新を差分更新できるようにしたい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#181]
**Is your feature request related to a problem? Please describe.**
LatteArtの管理画面をテストする際
複数の管理画面を開きたいことがあるが複数windowに対応しておらずデータの巻き戻りや欠損が生じしてしまい、操作不能となってしまう。
原因は、プロジェクトデータを更新する際に画面に保持しているプロジェクトデータをまるまるリクエストに渡してしまっているため。
（2画面以上で管理画面を開き、新しいwindowで管理画面を操作した後、古いwindowで管理画面を操作するとバグる）
対策としては、差分のみの更新に変更すればデータの巻き戻りや欠損は最低限に抑えることができる（操作不能にもならない）

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knukio** [comment]
API分割済みのためクローズ
