### ISSUE TITLE
resumeしてキャプチャー再開するとき、キャプチャー終了時のURLからキャプチャーを再開したい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#182]
**Is your feature request related to a problem? Please describe.**
現在resumeしてキャプチャーを再実行すると、テスト結果開始時のURLからキャプチャーを再開する
テスト結果のオペレーション情報にはURLを含んでいるので、終了したURLから再開できるようにしたい。
※ ログイン画面があるページでは上手く行かないので、テスト結果同士を組み合わせて実行ができると便利かも
ログインのみのテスト結果 + ログイン後のテスト結果 で実行する等

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.10.0の現状では，一時停止後に再開した場合は，テスト対象ブラウザが閉じられることなくテストは継続する．
本件におけるresumeとは，「テスト終了」後に「テスト開始」を押下した場合と考えるが，
その場合にヘッダー左に表示されている「URL」ではなく，最終アクセスURLから再開したい，との要望とみられる．
しかし，前述の通り，その場合はテストの「一時停止」機能を使うことを想定しており，運用対処可能とみられる．
本件はクローズとする．
