### ISSUE TITLE
サーバ設定を外部化する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#186]
現状ハードコーディングされているlatteart、latteart-repository、latteart-capture-clのサーバ設定(デフォルトのポート番号など)を設定ファイルに外部化する。

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0では，デフォルトのポート番号などのサーバ設定は外部ファイル化（launch.config.json）されている．クローズとする．
