### ISSUE TITLE
キーワードで画面遷移を定義する機能の機能改善

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#190]
* キーワードが多くなる場合に備えて，キーワードを優先順位を矢印だけでなく順位を直接入力できる機能の追加
* 各キーワードごとに有効化/無効化できる機能の追加
* キーワードだけでなく，タグのidなどの要素も条件に加える
  * 以下のような，headerとfooterに同一キーワードが使われていて，headerの文字列に意図して画面定義したい場合に有効だと思います．
    * 設定画面
    ![図1](https://user-images.githubusercontent.com/9267473/160573098-d255a906-329a-4d2f-83ef-0d2fd93b5a07.jpg)
    * 画面遷移図と各ページ(url1,url2,url3)のソースコード
    ![図2](https://user-images.githubusercontent.com/9267473/160573195-8ab35cba-3848-412f-a7a4-4c1459c362aa.jpg)
      * url1(TOPページ)→url2(社員１)→url3(社員２)と遷移した
      * TOPページと社員ページの2つの画面が生成されることが意図する結果であるが，TOPページの1つに集約されてしまっている

**Comment by knukio** [comment]
解決済みのためクローズ
