### ISSUE TITLE
複数テスターを想定した際、結果フォルダを共有しづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#191]
**Is your feature request related to a problem? Please describe.**
- 現状の仕様だと、複数テスターがいる場合テスト実施後に結果フォルダを共有する必要があるかと思いますが、どのフォルダがどのセッションに対応しているかわかりづらいと思われます。
- ツールから過去のセッションを見る場合テスト結果名で表示されますが、フォルダーを直接見た際にも名前が付与されているとわかりやすいと思われます。

フォルダを直接見て判断できるようにするか、複数テスターのフォルダを表示する機構を別途設けるか等、どのような方法がよいか検討が必要。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knukio** [comment]
管理ツールから記録ツールを起動できるようになり、ファイルの共有が不要になった。
しかし、別ネットワークの場合エクスポートが必要であり、エクスポート時のファイル名は分かりにくい

**Comment by masaki-tajima** [comment]
エクスポート時のファイル名を「test_result_日付時刻」でなく「テスト結果名_日付時刻」のようにして，解決できないか．
