### ISSUE TITLE
管理ツールの編集画面にて、ストーリー選択欄で何ができるのか分かりづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#196]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
本件，おそらく古い時期に起票されたため具体的にどのページの何を指しているか不明．
v2.4.0時点の管理ツールのマニュアルでは，一通り機能の説明はなされている．
今後も事業会社等のフィードバックを受けながら，継続的なドキュメント整備・UI改善を行っていく方針のため，本件は一旦クローズとする．
