### ISSUE TITLE
ビューアモード時にて、タグの除外設定等は設定できなくとも、参照はできるようにしたい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#197]
**Is your feature request related to a problem? Please describe.**
カバレッジに何故タグが出てこないのか等がわからないため

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.10.0現在，管理ツール・記録ツールの両方において，設定画面から画面要素カバレッジは参照可能である．
本件，クローズとする．
