### ISSUE TITLE
画面遷移図において、「browser_back(browser_forward):」の画面遷移矢印が表示される

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#198]
**Is your feature request related to a problem? Please describe.**
表示しないようにする

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
戻る・進むによる画面遷移が行われたことを示しても問題ないとみられる．よってクローズとする．
