### ISSUE TITLE
記録された操作をそのまま再生するテストスクリプト生成機能の検討

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#199]
**Is your feature request related to a problem? Please describe.**
オプションで現行の方式（画面遷移網羅）と本方式を採用できるようにする
1つのテスト目的を1つのテストケースと想定
テスト目的の開始画面がテスト開始画面ではない場合、最初にその画面まで遷移するコードを挿入する
POを利用する
テストで行われた画面遷移をそのままの順番で実現するように適当なメソッドをつなぎ合わせる（画面遷移のpathが得られれば現行と同じ仕組みで実現可能？）

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knukio** [comment]
#14 と同一のためクローズ
