### ISSUE TITLE
記録ツールの履歴再生機能が正常動作しない

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#20]
**Describe the bug**
記録ツールの履歴再生機能について、ボタン押下後、再生用ブラウザは立ち上がるものの自動操作が実行されない。  
また、その状態で「履歴再生を中止する」ボタンを押しても反応がなく、他の機能も利用できなくなってしまう。  

**To Reproduce**

1. 記録ツールを起動
2. 記録ボタンを押下して操作を記録し、記録停止ボタンを押下
3. 「履歴を再生する」ボタンを押す

**Expected behavior**
「履歴を再生する」ボタン押下時に以下の挙動を期待する  
 - 画面操作を自動で再生する  
 - 「履歴再生を中止する」ボタンにて再生を中止できる  

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome 97
 - Version: 2.0.0

**Comment by s151013** [comment]
v.2.1.0で修正のためクローズ。
