### ISSUE TITLE
スクリプト生成で、リンクの中に空白文字が入っている場合にも良いロケータを生成する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#201]
**Is your feature request related to a problem? Please describe.**
現状、空白文字が入っているリンクに対してはXPathを使っている。
空白文字が入っているリンクをlinkTextで補足しようとするとエラーになる
記録されたelementのvalueをlinkTextかpartialLinkTextを用いて補足することを想定
例えば、`<br>`が入っていると生成スクリプトに改行がそのまま反映されシンタックスエラー
空白文字含むものをlinkTextで補足する方法があるのかを検討
nbsp, tab, `<br>` が記録時にどう記録されているかを確認

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
`<br>`とあるが，正しくは特殊文字表記の`&lt;br&gt;`とみられる．
<br>であればv2.7.1では再現しない（修正済み）
