### ISSUE TITLE
記録ツールにて、履歴をリセットする際にポップアップ画面を追加する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#204]
**Is your feature request related to a problem? Please describe.**
リセットボタンを誤って押してしまった場合、即時にリセットされてしまう。
他にも、リセットされているのか、されていないのかを視覚的にわかりやすくするため。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
現状，「リセット」という文言と，実際の挙動とが一致していないようにみられる．
一般的なリセットのイメージは，現在入力されている文字列や追加されたデータ等をクリアして（すなわち**破棄して**），再度何も追加されていない状態に戻す処理を示す．

現状の挙動ではこの「破棄」する処理は行われておらず，それまでに追加されたテスト結果は保存され，新たなテスト結果としてテスト開始可能な状態を作り上げるため，用語としては「（テストの）新規作成」に近いとみられる．
