### ISSUE TITLE
webpにパスを通さず画像圧縮設定をONにして記録開始した際の警告メッセージに後からwebpのパスを通した際の注意事項の旨を追記したい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#205]
**Is your feature request related to a problem? Please describe.**
webpのパスを通した後、liatteart-repositoryを再起動しないといけないので、欲を言うと警告文に追記した方が親切である。
その旨を警告メッセージに追記したい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
#206 に集約．クローズとする．
