### ISSUE TITLE
画面要素カバレッジの設定のタグ一覧の枠サイズが同一ではない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#207]
**Is your feature request related to a problem? Please describe.**
記録ツールの画面要素カバレッジの設定にあるタグ一覧の一番下の項目の内枠が外枠に合わせて大きくなっているため、見栄えとして良くないので、統一したほうがいいのではないでしょうか。

![image](https://user-images.githubusercontent.com/9267473/160578422-39ccd644-9949-48e2-b1fb-bc476481b2ea.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.9.0よりVuetify2バージョンアップの影響で，本事象解消．クローズとする．
