### ISSUE TITLE
特定のページで画面遷移を行ってもinput要素が入力値一覧に表示されない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#209]
**Describe the bug**
キャプチャー実施中、じゃらん（ https://www.jalan.net/ ）トップ画面より，宿泊地，日付等を指定後，「検索する」ボタン押下すると 画面は遷移するが、ボタン上部のチェックボックスやラジオボタンの値が入力値一覧に表示されない

**Comment by masaki-tajima** [comment]
v2.10.0，Windows．Chrome v114 で再現確認．
画面遷移が正しく記録されていないように見える．

テスト結果zip : 
[session_20230616_111321_20230616_111548.zip](https://github.com/latteart-org/latteart/files/11765466/session_20230616_111321_20230616_111548.zip)

**Comment by fujiwr** [comment]
現状、ウィンドウ切り替え(switch_window)を現在画面遷移図、入力値一覧に出力しない実装になっている。
また、新規ウィンドウを開く(タブ)と既存のウィンドウ切り替えは現状の実装では区別がつかないため、新規ウィンドウが開かれた旨を表現する特殊なテストステップを新設する必要がある。
