### ISSUE TITLE
画面スナップショットの配置先とファイル名の改善

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#21]
**Is your feature request related to a problem? Please describe.**
v2.0.0では、全セッションの画面スナップショットが同一フォルダに格納されるため、抽出が困難になってしまっている。

**Describe the solution you'd like**
v1.7.5以前と同様の仕様としてほしい  

**Describe alternatives you've considered**
セッション毎にフォルダを作成し、その中に画面スナップショットを配置する  

**Additional context**
画面スナップショットのファイル名もv2.0.0では英数字ランダムになっているため、v1.7.5以前と同様の仕様としてほしい

**Comment by knukio** [comment]
v2.1.0から、セッションをエクスポートすることでセッション単位でのスクリーンショット一覧を確認することが可能になりました。
ファイル名については今後検討しますが、どのようなユースケースを想定されていますでしょうか？

**Comment by ndsuzuki** [comment]
ユースケースですが、過去ツール利用の実績として以下用途がありました。    
-  LatteArtを証跡取得ツールの位置づけでスクリプトテスト中で利用しており、スナップショットを証跡として利用  
- システムの操作マニュアル作成のため、スナップショットをマニュアルに張り付けて利用

**Comment by knukio** [comment]
LatteArt上から表示しているスクリーンショットをダウンロードできるようにすることでより簡単にユースケースを満たせると思いますのでその方法で対応予定です。
