### ISSUE TITLE
レビュー画面のシーケンス図にて起票済バグがわかりづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#212]
**Is your feature request related to a problem? Please describe.**
コンテキストメニューを開かないと起票済かどうかわからないため、吹き出し自体にその旨が分かるような表示があるとよい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knukio** [comment]
現状、reportedと表示されるためクローズ
それとは別に色を設定できると良い
