### ISSUE TITLE
SELECTタグを記録した際の操作一覧のテキスト列表示改善

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#214]
**Is your feature request related to a problem? Please describe.**
記録ツールでSELECTタグの要素を記録した際、シーケンス図下部の操作一覧の「テキスト」列にSELECTの選択肢すべてが表示されるが、選択した項目の表示文字列だけが表示されているほうがわかりやすいと思われる。
(※選択肢が膨大になると操作一覧にホバーした際にポップアップされる詳細情報が長すぎて画面からはみ出ることもあり、その対処としても選択した項目のみ表示する形がよいのではないか)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
操作一覧の「テキスト」列の表示はあくまで参考情報であり，大量に表示される場合でも表示しきれない場合は省略される．
ホバーによる全文表示においても，特段支障が出るケースは考えにくい（ホバーして，他の操作が一切できなくなるわけではない）
issue整理のためクローズとする．
