### ISSUE TITLE
buttonタグのtextに改行が含まれる場合，生成されたテストスクリプトでロケータエラーが発生

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#215]
**Describe the bug**
Spring PetClinic の "Find Owner" "Add New Pet" などで確認
ロケータはpartial link textが生成される

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by knukio** [comment]
#578 と同じためクローズ
