### ISSUE TITLE
記録ツールおよび管理ツールのlocale選択欄の文字列の多言語化

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#216]
**Is your feature request related to a problem? Please describe.**
記録ツール、管理ツールの「locale」プルダウンリストのラベルは現在「locale」固定になっているが、日本語を選択した場合は「言語選択」などの文言に切り替わってほしい。 また、選択肢自体も日本語を選択した場合は、「ja」や「en」から「日本語」や「英語」に切り替わってほしい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
localeを「言語」にするとより親切という議論であるが、「ja」のみでも言語切り替えを示すことが容易に理解可能である。
issue整理のため、クローズとする。
