### ISSUE TITLE
管理ツールトップのフッタを表示非表示切り替え可能にする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#217]
**Is your feature request related to a problem? Please describe.**
管理ツールのフッタ(マトリクスの凡例が書かれている部分)のスペースが広いため、開閉できるフッタにするか凡例(ヘルプ)ボタン等でダイアログを表示する形にするなどしたほうが良い。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
一般的な解像度のフルHD画面で最大化した場合は，フッターの縦幅は画面全体の1/5程度であり，特に邪魔となる印象は感じられなかった．
issue整理のためクローズとする．
