### ISSUE TITLE
履歴画面の履歴管理テーブルのフィルタ機能の操作感について見直し

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#218]
**Is your feature request related to a problem? Please describe.**
履歴画面の履歴管理テーブルのフィルタ機能の操作感について見直しをしたい。
現状では以下の案があり、使用感を確認したい。
**Describe the solution you'd like**
[As Is]
1. シーケンス図および画面遷移図のダイアグラムをクリックしたとき、画面下部の履歴管理テーブルの履歴がフィルタリングされる。
1. フィルタリセットボタンを押下すると、フィルタリングが解除される。

[To Be]
1. [As Is]と同様。（ただし、クリックした箇所は選択されていることがわかるように強調する。） ~~2. １．でクリックした箇所をもう一度クリックすると、フィルタリングが解除される。~~
1. ダイアグラムの空白部をクリックしたとき、フィルタリングが解除される。

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
#484 により改善するため，クローズとします．
