### ISSUE TITLE
管理ツールのストーリー画面にて、取り込みテスト名横の時間が経過時間ではない

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#22]
**Describe the bug**
管理ツールのストーリー画面について、「実行結果の取り込み」ボタンを押し該当テストを取り込むと、テストの名称と時間が表示されるが、経過時間ではないように見える。

**To Reproduce**
1. 管理ツールのストーリー画面に遷移する
2. 「実行結果の取り込み」ボタンを押し対象のテストを選択する

**Expected behavior**
経過時間の表示を期待している

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome 97
 - Version 2.0.0

**Comment by knukio** [comment]
#58 と同じと思われる
v2.2.0 で解決
