### ISSUE TITLE
低解像度で管理画面を開くと品質管理タブがクリックできない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#220]
**Describe the bug**
解像度1024 * 768の画面で管理画面を開くと
ヘッダーにある「品質管理」タブがボタン群の下に入り込んでしまいクリックできない
※ 高解像度でもブラウザの表示領域を小さくすれば同一の事象が発生する

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
現状は推奨ブラウザがChromeやEdgeで，要求スペックも高い（Core i7/RAM 8GB以上）ため，解像度の低いPCでの使用は考えにくく，想定していない．
v2.4.0で確認したところ，品質管理の「品」の文字がかろうじて表示されるため，横幅1024px以下でもクリック可能であった．
クリック可能であるため，クローズとする．
