### ISSUE TITLE
管理ツールでの特定操作時、開発者ツールに不要と思われるデバッグ情報がコンソール出力されている

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#221]
**Describe the bug**
管理ツールでの特定操作時、開発者ツールに不要と思われるデバッグ情報がコンソール出力されている。

- テスト計画編集画面のテストマトリクス作成ダイアログから「作成」ボタンを押下したとき、「null」がコンソール出力される。
- 管理ツールTOPの「詳細レポート出力」ボタン押下時、「*************」とコンソール出力される。

**To Reproduce**

**Expected behavior**
上記、2件のデバッグ情報は出力されないようにする。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0で再現せず．クローズとする．
