### ISSUE TITLE
履歴画面のシーケンス図モデルにおいて、図中のノードの文字がノードの枠を突き抜けている。エッジの文言に見切れがある

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#222]
**Describe the bug**
履歴画面の画面遷移図モデルにおいて、図中のノードの文字がノードの枠を突き抜けている。エッジの文言に見切れがある。

**To Reproduce**

**Expected behavior**
画面遷移図が正常に表示される

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by knukio** [comment]
画面遷移図モデルでは省略されるようになっている。
一方シーケンス図モデルでは文字列が長いと枠をはみだしている。

**Comment by masaki-tajima** [comment]
現状，特段見栄えに致命的な影響は無い．
issue整理のためクローズとする．
