### ISSUE TITLE
テストコード生成機能でプロキシ認証を行う場合に実行できない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#226]
**Describe the bug**
Proxy情報を入力画面を経由(以下①→②)してテストを実行した場合、生成される「test.spec.js」で呼び出すクラス名がプロキシ画面(①)、実行メソッド名が試験対象(②)となるため実行エラーとなる。
- ①プロキシ情報の入力画面(NoTitle.page)
- ②試験対象URL画面

- 参考
  - https://rdk.me/proxy-selenium/
  - https://stackoverflow.com/questions/55582136/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python

**To Reproduce**

**Expected behavior**
- 対処方法1
  1. 手動で認証プロキシを記憶させる事が可能な「proxy switchy omega」などのプラグインをseleniumで開いたchromeにインストールし，ユーザデータを作成
  1. SeleniumのChromeOptionsに作成しておいたユーザデータを設定する．

- 対処方法2（ヘッドレスでは動かない）
  1. 自作のchrome拡張機能を作成（生成）しておき，SeleniumのChromeOptionsに設定する．
- LatteArt側の対処
  - wdio.conf.jsにユーザデータや拡張機能を読み込ませる設定を簡単に追加できるようにしておく．

**Screenshots**

**Desktop (please complete the following information):**
 - Version [0.5.0]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
やや特殊ケースであり，issue整理のためクローズとする．
再度要望があった際には別途検討する．
