### ISSUE TITLE
ストーリー画面にあるメモ欄の記載で改行できるようにしてほしい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
#262 の要望を本件で解決できる可能性があるため，本件の優先度を上げる．

**Comment by masaki-tajima** [comment]
https://github.com/latteart-org/latteart/issues/278 も関連．
