### ISSUE TITLE
アイコン・メニューの整理

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#228]
**Is your feature request related to a problem? Please describe.**
アイコンが多く、UIが複雑になっている。
例えば、セッション単位でのテストスクリプト生成はメインのユースケースではないので目立たなくさせたい．
メニューバーから選択などに変更する。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0で，記録ツールに関してはヘッダのハンバーガーメニュー化を行った．現状，整理されたとみなし，クローズとする．
