### ISSUE TITLE
チャーター画面の添付ファイルに空のテキストファイルを添付して保存しても保存された実ファイルが空になっていない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#229]
**Describe the bug**
チャーター画面の添付ファイルに空のテキストファイルを添付して保存しても保存された実ファイルが空になっていない。(uｫZという文字が書き込まれている)

**To Reproduce**

**Expected behavior**
空のテキストファイルになること。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fujiwr** [comment]
#298 にて合わせて確認するため本チケットはクローズ。
