### ISSUE TITLE
ツール上から不要なセッションデータ(テスト結果)を削除できるようにしたい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#230]
**Is your feature request related to a problem? Please describe.**
記録中の誤操作や記録ツール異常終了によって生成された不要なセッションデータ(テスト結果)をツール上から削除できるようにしたい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nemotoaa** [comment]
記録ツールからテスト結果を削除する。リモート、ローカルの考慮不要。
