### ISSUE TITLE
テストスクリプト生成で，ブラウザの進む・戻るを考慮していない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#231]
**Describe the bug**
ブラウザの進む・戻るがテストコードに反映されるようにしたい。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Version [0.5.0]

**Additional context**

**Comment by masaki-tajima** [comment]
v2.10.0では，テストスクリプト生成時に「操作そのままの出力」が可能である．
ブラウザバック操作は「Do 'Browser back'# Please implement it manually」のように記述され，編集を行う必要はあるが，コードへの反映はされている．
運用対処可能とみられるため，issue整理のためクローズとする．
