### ISSUE TITLE
リプレイで特定の操作を除外できるようにする

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#232]
**Is your feature request related to a problem? Please describe.**
リプレイ時に特定操作が原因でうまく実行ができなくなるケースへの回避策として、操作一覧の特定の行を除外できるようになるとよい。
現状複数行選択はできるが、歯抜けで指定はできないため、例えばCTRL＋選択で1つ1つ選べるようにして、さらに全選択もできるようにすることで、「全選択＋個別で解除」のような形でできると良い。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
自動操作機能（ #408 #409 #407 #475 等）により，本改善が実現するため，クローズとする
