### ISSUE TITLE
入力フォーム画面のセッションから生成したテストスクリプト実行時、not a valid XPath expressionが発生する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#234]
**Describe the bug**
次のwebページを記録したセッションからテストスクリプト生成時、エラーが発生する。
https://www.rakuten.co.jp/myrakuten/help/
[エラー内容]
```
invalid selector: Unable to locate an element with the xpath expression /HTML/BODY/[NAME()="DIV"][2]/[NAME()="DIV"][2]/[NAME()="FORM"][1]/[NAME()="INPUT"][3] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '/HTML/BODY/[NAME()="DIV"][2]/[NAME()="DIV"][2]/[NAME()="FORM"][1]/[NAME()="INPUT"][3]' is not a valid XPath expression.
(Session info: chrome=87.0.4280.88)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.8.0で再現しないためクローズとする．
