### ISSUE TITLE
記録ツールで履歴をリセットしても画像表示領域のスクリーンショットが消えない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#237]
**Describe the bug**
記録ツールの「履歴をリセット」ボタンを押下して履歴をリセットしても、画像表示領域に表示されているスクリーンショットが消えない。

**To Reproduce**

**Expected behavior**
リセットしたらスクリーンショットも消えること。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by knukio** [comment]
対応済みのためクローズ
