### ISSUE TITLE
管理者ツールのレポート部で，バグと気づきがどの目的と紐付いているのかを見たい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#239]
**Is your feature request related to a problem? Please describe.**
管理者ツールで、テスト結果を読み込むとテスト目的やバグ・気づきが表示される。
現在の表示だとどのテスト目的のテスト中にバグを発見したか、気付きがあったかがわからないので、わかるようにしてほしい。
セッションのレビューをするとこれは表示されるが、セッション一覧画面で見たい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
スナップショット出力を行うと，Excelにより，どの目的において気づきがあったかが確認できる．
管理ツールのストーリー画面においても，テスト目的に内包する形で，気づきを表示できたほうが良い．
また，従来通り「全ての気づき」を見たい場合に備えて，全てのテスト目的を1クリックで同時展開できるような機構も備わっているとなお望ましい．

- テスト目的A
  - 気づきa
  - 気づきb
  - 気づきc
  - ...
- テスト目的B
  - 気づきd
  - 気づきe

**Comment by fujiwr** [comment]
- 「テスト目的・気づき」という文言で、テスト目的とそれに付随する気づきを入れ子で表示するようにする。
- 全てのテスト目的の開閉を一度に開閉できるボタンを新設する。
- テスト目的の詳細ダイアログを表示するボタンを表示する。
