### ISSUE TITLE
BTS連携機能がほしい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#240]
**Is your feature request related to a problem? Please describe.**
バグ管理は自動ではなくてよいので、BTS連携機能を付与して欲しい

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
起票状態を管理するreportedタグがあり，管理ツールストーリー画面からも一覧で確認可能である．
issue整理のため本件クローズとする．
