### ISSUE TITLE
バグ報告時にスクリーンショットに追加の情報を加えたい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#241]
**Is your feature request related to a problem? Please describe.**
ある操作をマークしたり、画像に丸とか付けられるとよい

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
画像を加工するための実装は工数が多く、現状の気づき（任意の文字列情報）のみで運用対処可能である。
issue整理のため、クローズとする。
