### ISSUE TITLE
生成スクリプトの出力先表示がlocalhostから始まっている

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#243]
**Describe the bug**
生成スクリプトの出力先について '[http://127.0.0.1:3002/test-results/～](http://127.0.0.1:3002/test-results/%EF%BD%9E)' と表示されるため、実際の出力先がわかりづらい。

**To Reproduce**

**Expected behavior**
出力先の絶対パス、または相対パス「/test-result/～」での表示。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Version [1.0.2]

**Additional context**

**Comment by knukio** [comment]
リンクからダウンロードできるようになったため解決
