### ISSUE TITLE
レビュー画面でレビューコメントの記載や新規セッションの作成ができるとよい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#250]
**Is your feature request related to a problem? Please describe.**
テスト管理者はテスト結果を受け取った後、必ずレビュー画面でレビューを行う流れになるが、レビュー画面でテスト管理者がコメントを残したい場合、テスト管理者が別途テキストエディタ等でメモしておく必要があり不便。
レビュー画面でコメントを記載でき、そのうえでテスト管理者がレビュー画面からセッションを作成できるようになれば便利ではないか。
(その際、レビューコメントを参考に次回セッションのメモを作れるようになる等)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
セッションへ記載するメモ欄があり，運用対処可能とみられる．
issue整理のため，本件クローズとする．
