### ISSUE TITLE
起動スクリプトポート変更時、変更箇所を減らせるようにしたい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#253]
**Is your feature request related to a problem? Please describe.**
起動スクリプトにポート変更箇所が複数ある。
変更漏れが発生する可能性があるので同一変更箇所はまとめたり、定数で変更可能にしたい。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fujiwr** [comment]
修正済みのためクローズ
