### ISSUE TITLE
画面遷移を行うまで、同じ入力画面にて複数回入力値をいれても一覧に入力した要素が並列に記載されない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#254]
**AsIs**
（エラーメッセージの確認等を目的とした）ログイン処理の失敗を連続して行う際、画面の更新を行わなければ入力値一覧に要素が並列に記載されない。
画面遷移が発生しないため、入力値一覧には最後に入力した値が表示される。
![image](https://user-images.githubusercontent.com/9267473/160595333-b8570aa9-77a9-4dc9-a9d6-751003d2f3d3.png)

**ToBe**
画面遷移されなくても入力値一覧に入力した値が列挙される。
![image](https://user-images.githubusercontent.com/9267473/160595401-5397bbfb-b885-4d0d-9925-f50795272483.png)

**Environment**

Sock Shop という [靴下ECサイト](https://github.com/microservices-demo/microservices-demo)のサンプルアプリケーションのログイン処理部分。

```shell
# git, docker, docker-compose のインストールは省略
$ git clone https://github.com/microservices-demo/microservices-demo
$ cd microservices-demo
$ docker-compose -f deploy/docker-compose/docker-compose.yml up -d
<: snip>
```
`http://localhost`に接続。Environment

**To Reproduce**
LatteArt 記録ツールを起動し、以下の手順を実施する。

1. login をクリック
1. user/password (正常パターン)を入力し、login をクリック(画面遷移される)
1. logout をクリック
1. login をクリック
1. userrrrrrr/passworddddddd (失敗パターン) を入力し、login をクリック
1. 失敗のメッセージが画面遷移せずに表示される
1. uuuuuuuser/ppppppassword (失敗パターン) を入力し、login をクリック
1. LatteArt 記録ツールにて確認

**Comment by masaki-tajima** [comment]
submitを検出することで，入力値一覧に表示させることはできないか？

現状，入力値一覧に「1回目」「2回目」...と表示されている入力値は，submit後に実際に画面遷移が行われた入力値に限り表示されている．
しかし，テスト実施時には，submitするもエラーとなって画面遷移が行われないパターンが存在する．
また，submitに限らず，特殊な実装によりsubmit相当の処理が行われる場合も考えうる．
そのような場合でも，例えばユーザーの手動操作によって，特定の入力操作を入力値一覧に入力値として追加させることで本事象を改善できないか．

**Comment by fujiwr** [comment]
- 画面遷移図のノードクリック時の挙動
  - 画面遷移時のトリガーとなる画面要素が複数回登場した場合、履歴内でその画面要素をクリックした各地点での入力値セットをすべて入力値一覧に表示する。
    - 例: ボタンA押下時、初回は画面遷移無し(バリデーションエラー発生時など)、２回目はB画面に遷移したというケースの場合、入力値一覧には、画面遷移していないときの入力値セットを「1回目」と、B画面に遷移したときの入力値セットを「2回目」として表示する。
    - 画面遷移が一回もされていない場合は当該画面の入力値一覧は何も表示しない(従来通りの挙動)
- 画面遷移図のエッジクリック時の挙動
  - 画面遷移に成功した場合の入力値セットのみ表示する（従来通りの挙動）
