### ISSUE TITLE
記録ツールで操作のたびに発生するScreenshotの取得をON/OFFできるオプションを用意する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#256]
任意のタイミングでスクリーンショットの取得のON/OFFを切替できるようにする．

**Comment by masaki-tajima** [comment]
https://github.com/latteart-org/latteart/issues/275 の問題も本件で回避できる可能性がある（回避策1）．
やや優先度を上げて対応したい．

**Comment by masaki-tajima** [comment]
#275 の解決のために本件を導入するのはやや不適との議論結果から，いったん優先度を下げる．

**Comment by masaki-tajima** [comment]
テストの一時停止機能により，テスト記録が一時停止されるため，スクリーンショットの取得機能も停止する．
スクリーンショットのみ一時停止するユースケースが多くないと想定するため，こちらの運用対処としたい．
本件クローズとする．
