### ISSUE TITLE
画面キャプチャツールで登録したバグを削除することができない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#258]
**AsIs**
画面キャプチャツールで登録したバグを削除することができない。  
バグの内容を削除した場合、OKボタンが非アクティベート化される。  
バグの内容に空白文字列を追加した場合、空白文字列がそのままバグとして登録される。
![image](https://user-images.githubusercontent.com/9267473/160596105-e12b5e45-b3ec-4e74-9b98-4886510264bc.png)

**ToBe**
バグを削除することができる。  
削除する方法は要検討。  
- 例
  - ①の部分に削除項目を追加する
  - ②の部分で概要・説明欄が未入力でOKを押下すると削除される
など

**To Reproduce**
1. 画面キャプチャツールで任意のバグを登録する
1. 登録したバグの交番で右クリック
1. バグの編集

**Comment by knukio** [comment]
シーケンス図から削除可能となっているためクローズ
#119 で操作一覧からも削除したい
