### ISSUE TITLE
記録ツール実行時、テストの目的とそれに紐づく気づきやバグを確認したい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#259]
**Is your feature request related to a problem? Please describe.**
テスターが記載したバグや気づきを一目で閲覧したい。
なぜなら、大量に気づきがあった場合にテストの観点抜け漏れを無くしたいため。

- 抜け漏れの例
  - テスト中に見つけた気づきを異なる処理部で確認する必要があるか、気づきの一覧から新たに目的を作成してテストをする

類似 issue: https://github.com/latteart-org/latteart/issues/239

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
#280 の実装により本件は解決すると想定．クローズとする．
