### ISSUE TITLE
管理ツールのテストマトリクスの設定で、観点の補足説明欄が欲しい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#260]
**Is your feature request related to a problem? Please describe.**
管理ツールのテストマトリクスの設定にて、観点を設定する際に例えば「例外フロー」に「〇〇の例外処理は対象外」などの補足説明を追加したいことがあります。
観点に対する「補足説明」欄のようなものがあり、マトリクス上から見えるようになっていると使い勝手が向上すると思われます。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
各観点に備考欄を設ける．後から編集も可能とする．

**Comment by masaki-tajima** [comment]
事業要望のためPriorityを1つ上げる．

**Comment by fujiwr** [comment]
- 観点の補足説明
  - 編集画面でのマトリクス作成ダイアログ・観点設定ダイアログで観点名の下付近で補足説明を入力可能とする。
  - 編集画面でのマトリクス表示時は、観点名にカーソルを合わせると補足説明が吹き出しで表示されるようにする。
  - プリセットの各観点の補足説明はチュートリアル資料の説明に従う。

**Comment by fujiwr** [comment]
テスト観点の説明の入力欄に「テスト観点の説明」というプレースホルダーを付与する。
