### ISSUE TITLE
管理ツールのテストマトリクスの設定で観点の表示順番を変更したい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#261]
**Is your feature request related to a problem? Please describe.**
管理ツールのテストマトリクスの設定にて観点の表示順番を変更できるようにしていただきたいと思っております。
あとから、よく使う観点を先頭に表示させたり、近くにグルーピングしたい場合がございます。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
有用な事業要望のため優先度を上げる．
https://github.com/latteart-org/latteart/issues/260 と合わせて改善したい．
