### ISSUE TITLE
管理ツールのテストチャーター部に「セッションの実施予定時間」を記入したい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#262]
**Is your feature request related to a problem? Please describe.**
管理ツールのテストチャーター部に「セッションの実施予定時間」を記入できるとありがたいです。

(メモ欄に書くこともできます、メモが盛沢山になってしまうので専用の記入欄が欲しいです。)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
ややピンポイントな改善要望であり，むやみにテストチャーター部の項目を増やすことが操作性を劣化させる可能性もある．
https://github.com/latteart-org/latteart/issues/227 を優先して，メモ欄を改行可能にすることで，本件の改善となるか検討する．

**Comment by masaki-tajima** [comment]
#227 でメモ欄を改行可能にしたため，こちらで解決すると想定する．クローズとする．
