### ISSUE TITLE
記録ツールのテストスクリプト生成ボタン押下後（生成中）に別操作可能

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#264]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.4.0で確認したところ，スクリプト生成中は別の操作は不可能であった．
テストスクリプト生成中は，他のメニューボタン等を押下できない．
おそらく別操作が可能であることをbugとした起票と思われるので，再現しないため本件はクローズとする．
（別操作が可能になることを期待した改善要望であった場合でも，スクリプト生成は数秒程度で終わるため，支障が無いと考える）
