### ISSUE TITLE
管理ツールのレポート部でバグや気づきの画面キャプチャを確認したい

### ISSUE THREAD

**Issue by masaki-tajima** [latteart-org/latteart#277]
管理ツールで、バグや気付きについて確認できるが、対象のキャプチャを見るためにはレビューモードでシーケンス図から対象のバグ等を見つける必要があり手間だと感じる。
レポート部の「詳細」ボタンから、対象の気づき起票時の画面キャプチャを確認できるとうれしい．

**Comment by fujiwr** [comment]
気づきに紐づく画像がある場合はそれを優先して表示し、無ければ操作に紐づく画像を表示する。

**Comment by fujiwr** [comment]
ダイアログ内の画像をクリックすると、ポップアップで拡大した画像が表示されるようにする。
