### ISSUE TITLE
セッションの「実施されたテスト」に記載されている目的に詳細がない場合、空白行で展開されてしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#28]
**Describe the bug**
実施されたテストに記載されている目的の矢印を押すと目的の詳細が出てくる仕様のようだが、詳細を書いていない場合、 矢印を押しても展開だけされて何も出ないのは何を表示する部分なのかぱっと見わからない。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
詳細があれば詳細が表示され、詳細が無い場合には何も表示されない仕様である。
現状、問題は無く、issue整理のためクローズとする。
