### ISSUE TITLE
管理ツールのストーリー画面でセッションに空のテキストファイルを添付できない

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#298]
**Describe the bug**
管理ツールのストーリー画面でセッションに空のテキストファイルを添付できない。（添付しようとしても無反応）

**Expected behavior**
空のテキストファイルを添付できること。
また、セッション画面で添付時と同じ内容のファイルをダウンロードできること。

**Comment by masaki-tajima** [comment]
空のファイルを添付するケースが少ない．
issue整理のため本件クローズとする．
