### ISSUE TITLE
生成されたテストスクリプトを実行すると、waitが一切無いためelementが見つからないエラーが発生することがある。

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**
elementに対する操作の前に、対象elementが存在するかどうかのチェックを入れて、存在するまで待つようにスクリプトを生成することで対応できると思われる。 

→findElement+待つという機能を持つものがseleniumにあると思うので、それを使う方がいいと思われる。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
latteart-org配下で公開しているtest-script-runnerにて実行いただいているのであれば、
wdio.conf.jsのwaitforTimeoutで設定されている時間(10000ms)までは待つものとなっている。
再現用のページ（jsで動的に3秒待ってから要素を表示するページ）を作って確認したところ，
エラーを確認することができなかった．(要素表示までの時間を10秒以上にすればエラー:element not foundになる)。

本issueには「waitが一切無い」とあるが、実際には（デフォルト値として）10000msまで待つものとなっている。
一方で、test-script-runnerを使わず、独自にwebdriverioのCLIを使用等されていると、0msで一切待たない状態となりえる。

その他、手元でいくつか検証したところ、たとえば画面幅の違いで表示される要素が異なるサイト
（スマートフォン向け・PC向けで分かれるサイト等）では、テスト記録時とtest-script-runner実行時で
開かれるwindow幅が異なり（記録時:最大化、実行時:900px程度)、要素が見つからないことがあった。

本エラーが出た環境は、以下のいずれに該当するか確認が必要．
・レスポンシブな画面で記録時と実行時で画面サイズが異なる
・レスポンシブではないが単純に見つからない（時間差で動的に表示される要素の場合はwebdriverioの待機時間が適切か)

**Comment by masaki-tajima** [comment]
事象再現しないため，issue整理のためクローズとする．
