### ISSUE TITLE
履歴管理テーブルにおいて、メモ・目的の有無でソートできるようにしてほしい

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#37]
**Is your feature request related to a problem? Please describe.**
大量操作を記録した場合、登録済の気づきや目的を記入した操作を抽出する際、記録ツール上で効率的に抽出する
手段がない。  

**Describe the solution you'd like**
登録済の気づきや目的を記入した操作を効率的に抽出する仕組みがほしい

**Describe alternatives you've considered**
履歴管理テーブルのソート対象にメモ、目的欄を追加しマークの有無で並び替えることで、抽出が容易になる

**Comment by masaki-tajima** [comment]
#280 で実現．v2.4.0より機能実装済み．クローズとする．
