### ISSUE TITLE
メモリ消費量の改善

### ISSUE THREAD

**Issue by knukio** [latteart-org/latteart#390]
約270ステップのテスト結果で約3Gのメモリを消費する場合があり、実用上問題がある。

各ステップ毎にInputElementsを保存していることが原因と思われる。
共通するデータをメモリ上に複製して保持しないようにする。

**Comment by fujiwr** [comment]
根本原因はバックエンド側でのインポート処理のバグ(coverageSourcesが異常に多く登録されてしまう)であったため、こちらを修正する形で対応する。
