### ISSUE TITLE
テスト結果を読み込まずに削除する

### ISSUE THREAD

**Issue by yoshimi-ikari** [latteart-org/latteart#401]
**Is your feature request related to a problem? Please describe.**
現在latteart-v2.5.0-winでは、テスト結果を削除するためには一度テスト結果を読み込まなければいけません。
このバージョンでは読み込みに時間がかかるので、複数回のテスト結果が存在している場合は非常に削除の手間がかかります。
テスト結果を読み込まなくても削除できる機能が欲しいです。

**Describe the solution you'd like**
「テスト結果の削除」を実行するとインポートしたテスト一覧が表示され、その中で選択して削除する。

**Comment by masaki-tajima** [comment]
テスト結果をエクスプローラのように容易に管理可能とする方法と合わせて検討する．

**Comment by fujiwr** [comment]
サイドメニューにテスト結果の一覧(エクスプローラのようなもの)を表示し、その中で削除や名前変更、その他テストスクリプト生成等単独のテスト結果に対する操作が行えるように実装する。

**Comment by fujiwr** [comment]
テスト結果一覧の行にカーソルを合わせた際、以下を表示する
- マウスカーソルを手の形のカーソルにする(ボタンと同様)
- ツールチップで「テスト結果を読み込む」などの文言を表示する
