### ISSUE TITLE
管理ツールからプロジェクトをエクスポートしてインポートすると設定が引き継がれていない

### ISSUE THREAD

**Issue by nemotoaa** [latteart-org/latteart#435]

**Comment by masaki-tajima** [comment]
## 整理
現状，インポート/エクスポート対象となっているものは以下のとおり．
- プロジェクトのインポート/エクスポート
  - プロジェクト情報（テストマトリクス・セッション等の管理情報）
  - テスト結果情報（セッションに取り込み，レビューを実施する際のテスト結果）
- 設定のインポート/エクスポート
  - 設定情報（画面遷移定義，自動入力，自動操作等の記録ツールの設定とほぼ同等の情報）


管理ツールで以上をインポート/エクスポートする場合の一般的なユースケースとして，他のPCや他のLatteArtバージョン等で作成されたプロジェクト情報（テスト結果・設定情報を含む）をそっくりそのままエクスポートし，インポートする場面が考えられる．
このとき，プロジェクトにテスト結果が含まれない場合の懸念として，セッションの内容を全て表示できない（目的や気づき一覧が表示されない，レビューができない）．
同様に，プロジェクトにテスト結果は含まれるが設定情報が含まれない場合の懸念として，画面遷移定義が適用されていないため，レビューが正しく実施できない．

よって，プロジェクトのインポート時には，テスト結果と設定情報も同時にデフォルトでインポートされることが一般には望ましい．
ただし，特殊なケースとして，テスト結果は不要で，テストマトリクスのみ継承して別のテスト計画を行いたい場合や，設定情報を他のもので上書きしたい場合も想定される．

## 対処方針
以上から，プロジェクトのインポート/エクスポートと，設定のインポート/エクスポートのボタンを統合して，「設定・プロジェクトのインポート」「設定・プロジェクトのエクスポート」とし，現行のチェックボックスは継承して
  - プロジェクト情報（テストマトリクス・セッション等の管理情報）
  - テスト結果情報（セッションに取り込み，レビューを実施する際のテスト結果）
  - 設定情報（画面遷移定義，自動入力，自動操作等の記録ツールの設定とほぼ同等の情報）
  の3つをデフォルトでチェック済みとするモーダルを表示し，ユーザが必要に応じてチェックを外すことで特殊なケースにも対応可能としたい．
