### ISSUE TITLE
自動入力設定でxpathの正規表現で指定した場合正しく動作しない

### ISSUE THREAD

**Issue by mamoru-x-yanagisawa** [latteart-org/latteart#440]
seleniumが解釈できる`//*[@id="snackbar"]`のような形式で正規表現と同じような表現ができるため、xpathでは正規表現は指定できないようにする(一致のみ)。

**Comment by fujiwr** [comment]
正規表現をユーザに指定させるのはやや複雑なため、contains（該当文字が含まれているか）でマッチさせるようなGUIにする。
※正規表現は指定できないようにする。
