### ISSUE TITLE
テスト計画編集画面にてテスト対象の表示順の変更が反映されない　※特定操作時のみ

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#47]
**Describe the bug**
テスト計画編集画面にて、テスト対象の項目の並びを変更しようと上下ボタンを押した際、特定操作時のみ反映されない  

**To Reproduce**
テスト計画編集画面にて以下操作を実施    
1. 「テスト対象」列の実施回数を上下ボタンを押して変更する  
2. 「テスト対象」の名称横の上下ボタンを押して並び順を変更しようとする  
3. 並びが一瞬変更されるがすぐに元に戻ってしまう  
※ 「1.」を実施しなければ並び順は変更される   

**Expected behavior**
「2.」実行により並び順が変更される  

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome 97]
 - Version [LatteArt2.1.0]

**Comment by masaki-tajima** [comment]
再現検証しましたが，実施回数を上下ボタンでやや高速に変更させたのちに，すぐテスト対象の並び順を上下させようとすると，まるでダブルクリックしてしまったかのように並び順がすぐ戻ってしまう現象でした．
実施回数をゆっくり変更させたのちに，並び順を変更すれば一応再現はしないようです．

**Comment by masaki-tajima** [comment]
高速にクリックせず，通常の速さ（１秒に１～１．５回程度）であれば再現しないため，クローズとする．
