### ISSUE TITLE
新規テスト実施支援<自動操作>:操作一覧での複数操作選択方法の改善

### ISSUE THREAD

**Issue by masaki-tajima** [latteart-org/latteart#474]
記録ツール履歴画面操作履歴のチェックボックスについて，常時表示させない方針とする．

ユーザは以下に示す手順および挙動で，操作の選択から登録までを行う．
1. 既存の「操作の登録ボタン」を押下する
2. 操作履歴にチェックボックスが表示される．また，付近に「選択のキャンセル」「選択した操作の登録」を意図するボタンが表示される
3. 2で「選択のキャンセル」ボタンを押下した場合は，チェックボックスを非表示にし，1以前の状態に戻す
4. 2で任意のチェックボックスを選択後，「選択した操作の登録」ボタンを押下した場合は，自動操作：登録ダイアログを表示し，チェックした操作に対して既に実装済みの操作の登録処理を行う．
5. 2でチェックボックスを一つも選択していないときは「選択した操作の登録」ボタンを活性化させない．（非活性でもボタンの文字列は識別できること）

特に2.における「選択のキャンセル」および「選択した操作の登録」ボタンについては，
- 既存の「フィルタリセット」の右に文字列でそのまま新設する
により実装する．

**Comment by fujiwr** [comment]
既存の「Shiftキー＋クリック」での複数操作選択を廃止し、チェックボックスでの複数選択に統合する形とし、モード切替は無しとする。

**Comment by fujiwr** [comment]
SHIFTを押しながらチェックボックスをチェックした場合、最後にチェックしたチェックボックスとの間をまとめてチェックできるようにする。
