### ISSUE TITLE
テスト対象ブラウザを × ボタンで閉じた場合、ブラウザを閉じてから記録が完全に終了されるまでに時間がかかる場合がある

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#510]
テスト対象ブラウザを×ボタンで閉じた場合、記録が完全に終了されてフロントエンドの記録ボタンの状態が切り替わるまでに時間がかかる場合がある。

**Comment by masaki-tajima** [comment]
v2.15.2現在では、アーキテクチャも大幅に変更しており、issue整理のためクローズとする。
