### ISSUE TITLE
操作履歴テーブルが昇順になってしまい少し見づらい

### ISSUE THREAD

**Issue by mamoru-x-yanagisawa** [latteart-org/latteart#515]
改ページを挟むと、直近の操作履歴が確認できなくなってしまうため

**Comment by masaki-tajima** [comment]
従来は降順表示であった．
降順では，最終操作が上に表示され，例えば直近10件が常に表示されていた．
また，操作が順次追加されていても，タイトル行が常に隠れず表示される．
昇順の場合，現状では改ページを挟むと，そこから1件ずつ表示される．
また，ページあたりの表示行数が多い場合は，下に追加され，タイトル行が隠れてしまう．

直近履歴が表示され，かつタイトル行も隠れないことが望ましい．
また，昇順・降順をブラウザ側で記憶でき，次回以降も当該順序で表示できると望ましい．
デフォルトを降順に戻すことも視野に検討したい．（昇順とした背景は，シーケンス図が上から下に流れることを意識して，履歴も上から下へ昇順とした）

**Comment by fujiwr** [comment]
１ページ内の項目数の選択肢を以下から選べるようにする。
- 100
- 200
- 500
- 1000
