### ISSUE TITLE
LatteArtのGUIおよびコンソール出力にバージョン番号を表示する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#52]
**Is your feature request related to a problem? Please describe.**
まずはGUIでバージョン表示を想定。コンソールの出力はそれでも必要であれば出力させるのはどうか。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masaki-tajima** [comment]
バグ報告時の情報にも有用であるため，コンソールおよび記録・管理の各ツールの全てで，どこかに表示させることとしたい．

**Comment by fujiwr** [comment]
各サーバのSTART時にコンソールとログファイルに出力するようにする。
