### ISSUE TITLE
記録ツールにて探索的テストを実施している途中でテストしているブラウザーが突然閉じられる

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#552]
**Describe the bug**
記録ツールにて探索的テストを実施している途中でテストしているブラウザーが突然閉じられ、記録ツールのメイン画面に切断された旨のエラーが表示される。

**To Reproduce**
どの機能で必ずブラウザーが閉じられるといった、条件がありません。（A機能で切断されることもあれば、B機能で切断されることもあります。逆に別のセッションでは、A機能でもB機能でも切断されなかったりします。）

**Expected behavior**
途中で切断されずに安定して探索的テストができるようにする。

**Screenshots**
撮るのを忘れました。再現出来たら取ります。

**Desktop (please complete the following information):**
 - LatteArt:v2.7.0
 - Chrome:107

**Additional context**
ログ及びコマンドプロンプトに表示されたエラーは残っております。  （スクリーンショットや記録ツールのエラー文言は残しておりません。）

**Comment by mineo-aya** [comment]
Chromeのバージョンを108にしたところ、突然ブラウザーが落ちるということはなくなりました。（原因が不明なため、これが原因だったのかもわからないのですが。）Edgeのバージョンを108で試しても、問題はありません。  
ただ、送付させていただいたコマンドプロンプトに出るエラーは、chromeが108になっても出力されます。Edgeのバージョン108ではコマンドプロンプトにエラーは出ません。

**Comment by mineo-aya** [comment]
また、送付したlogでブラウザーが落ちた時刻は12/1の  
11:28  
11:35  
11:42  
11:51  
です。

**Comment by masaki-tajima** [comment]
v2.15.2現在では安定しているものと想定します。
issue整理のためクローズさせていただきます。
