### ISSUE TITLE
「テスト目的を使用してテストする」のチェックを外した場合の「目的の追加・編集」の仕様を統一する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#56]
**Is your feature request related to a problem? Please describe.**
* 「メモを残す」ボタンを押下時、目的が入力できない
* 操作履歴の該当操作上で右クリックを押すと「目的の追加・編集」が選択可能

**Describe alternatives you've considered**
「テスト目的を使用してテストする」のチェックを外す場合の仕様を統一（テスト目的は入力できなくする
* `操作履歴で「目的の追加・編集」が選択できない`の対応
「テスト目的を使用してテストする」のチェックを入れた場合の仕様追加
* テスト開始時、テスト目的欄にプリセットで文字列が入力されている
  * テスト目的を後から追加したいテスターの心理は、「テスト対象を触ってから目的を決めたい」というものを想定
  * プリセット例
    * 例1) とりあえずテストを開始する
    * 例2) とりあえずテスト対象を見てから目的を考える
* その後の「メモを残す」ボタンや、操作履歴の該当操作上で右クリックを押下した場合、目的の追加・編集が可能

テスト目的追加・編集画面の文言変更
* 「詳細（非必須）」を「詳細（任意）」に変更。
**Additional context**

**Comment by masaki-tajima** [comment]
テスト目的の仕様については，統一を図るよりも柔軟性を残しておく方針としたい．
表示上の不自然な文言は指摘通りであるが，本件はクローズとする．
