### ISSUE TITLE
起票済みか未起票なのかがシーケンス図や一覧に色等で反映される。

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
起票済み気づき・バグ等の色分けはできているため、起票済みか未起票かが分かるように色や一覧にアイコンを付与する、といった対応を実施する。

**Additional context**

**Comment by masaki-tajima** [comment]
管理ツールストーリー画面から未起票・起票済み状態を確認でき，シーケンス図上から未起票・起票状態を確認するケースは少ないと想定している．
シーケンス図では，多数の気づきを一覧で表示できず，個別に1件1件表示するケースを想定している．
1件1件表示する場合では，気づきの参照によるモーダル表示により，起票済み/未起票状態が確認できる．
また，仮に本件の色分けを行うことで，気づきの他の属性であるbug（赤色）かnotice（紫？）等，色が多彩に使われるようになってしまい，視認性が悪化するとみられる．

よって，本件はクローズとする．
