### ISSUE TITLE
生成テストスクリプトについて、改行タグ(XXX<br/>XXX)を含むelementを取得しようとしてコード中に改行が入り実行時エラーとなる

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#577]
**Describe the bug**
生成テストスクリプトについて、半角スペース(XXX&nbsp;XXX)を含むelementを取得しようとして失敗する

**Desktop (please complete the following information):**
 - Browser [chrome80]
 - Version [LatteArt 0.5.0]

**Additional context**
古いバグなので、もうcloseなのか、他のissueとかぶるのかご確認お願いします。

**Comment by knukio** [comment]
#578 と同じためクローズ
