### ISSUE TITLE
記録ツールにて画面内のタブをクリックしても、該当のタブの画面に遷移しない。

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#579]
**Describe the bug**
記録ツールにて画面内のタブをクリックしても、該当のタブの画面に遷移しない。

**Desktop (please complete the following information):**
 - Browser [chrome80]
 - Version [LatteArt0.2.2,LatteArt 0.4.0,LatteArt 0.5.0]

**Additional context**
古いバージョンのため、改修済みなのか、他に同じissueが上がっているかご確認お願いします。

**Comment by masaki-tajima** [comment]
#169 と同様で，v2.7.1で修正済みのためクローズします．
