### ISSUE TITLE
生成テストスクリプトについて、複数ボタンが同一名称の画面について、区別がつかず1番目のボタンが押下される

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#580]
**Is your feature request related to a problem? Please describe.**
生成テストスクリプトについて、複数ボタンが同一名称の画面について、区別がつかず1番目のボタンが押下される

**Describe the solution you'd like**
要素の指定条件を追加して一意となるようなソースとしてほしい。

**Additional context**
古い要望のため、既にcloseなのか、他のissueがあるのかご確認お願いします。

**Comment by masaki-tajima** [comment]
以下zip内htmlの同一名称のボタン2つで確認．いずれもテストスクリプト上ではXpathではなくテキストで指定される．
`   <button type=“button” onclick="location.href='./test5.html'">リンク5</button>
   <button type=“button” onclick="location.href='./test6.html'">リンク5</button>`

[test.zip](https://github.com/latteart-org/latteart/files/10455417/test.zip)

**Comment by fujiwr** [comment]
テストスクリプト生成時に、screenElementsを確認し、該当要素が1つに特定できない場合はxpathをロケータとして使用するようにする。
