### ISSUE TITLE
生成テストスクリプトについて、保守性を考慮し、要素の指定方法についてはできるだけXpathを利用しない方式としてほしい。

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#581]
**Is your feature request related to a problem? Please describe.**
生成テストスクリプトについて、保守性を考慮し、要素の指定方法についてはできるだけXpathを利用しない方式としてほしい。

**Additional context**
古い要望のため、既にcloseになっているものや他のissueと同様かご確認お願いします。

**Comment by masaki-tajima** [comment]
v2.7.1では改善済み．
id, name, リンクテキストが無いときしか，Xpath を利用しない方式となっている．
