### ISSUE TITLE
iタグのクリックがテストスクリプトに生成されない

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#582]
**Is your feature request related to a problem? Please describe.**
記録ツールについて、階層構造を持つリンクを押下した際、押下位置によっては、リンクでないタグが記録されてしまう。
下記のソースの場合、押下位置によっては`<i>`が記録される。
```html
<li>
   <a class="ajax-link" href="https://xxxxxx/xxxxxt/">
      <i class="glyphicon glyphicon-tag"></i>
      <span> 遷移先画面</span>
   </a>
 </li>
```

**Describe the solution you'd like**
この際、左記の例では`<a>`が記録されるようになり、`<i>`への操作がテストスクリプト化されないのが問題。

**Additional context**
古い要望のため、既にcloseになっているか、他にissueはないかご確認お願いします。

**Comment by masaki-tajima** [comment]
#270 とおそらく同一．v1.4.1で再現．v2.7.1で改善済み．

**Comment by masaki-tajima** [comment]
コード内の記述から，bootstrap3のアイコン表記に関連したものと推定し，再検証した．
結果，`<i>`は幅10px程度のテキストの無いアイコン，`<a>`はテキストのある文字列となった．
`<i>`と`<span>`の両方を順にクリックして記録し，テストスクリプトを「操作ままの出力」のチェックを外して生成した場合，テキストのある`<span>`が優先され，`<i>`を要素とするテストスクリプトは生成されない．
「操作そのままの出力」のチェックを入れて生成した場合は，`<i>`を要素とするテストスクリプトが生成される．
