### ISSUE TITLE
記録ツール(bat)で立ち上がるブラウザを固定可能としたい

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#583]
**Is your feature request related to a problem? Please describe.**
記録ツールについて、capture.vbsより起動されるブラウザはchromedriver必須であることからChrome固定としたい。
（現在は端末設定「既定アプリ」の設定に依存）

なお、管理ツールについては、chromedriver不要で利用できるため、現行のまま指定不要としたい。

**Additional context**

**Comment by masaki-tajima** [comment]
現状（v2.7.1）では，テストブラウザはChromeの他はEdgeに対応済みで，ChromeDriverでなくEdgeDriverのみでも動作する．
capture.vbsより起動されるブラウザはchromedriver必須ではなく，正確にはテスト対象ブラウザにChromeを指定しテスト開始した場合のみ必須である．

一方，capture.vbsより起動されるブラウザをChromeまたはEdgeに固定することを可能とするオプション（例えばvbsの編集等により実現）を追加することはユーザビリティ向上に有益である．

**Comment by fujiwr** [comment]
起動スクリプトの設定ファイルにて、LatteArt起動時に使用するブラウザを指定可能とする(デフォルトは規定のブラウザ)。
