### ISSUE TITLE
管理ツールよりスナップショット出力したExcelの出力情報改善

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#585]
**Is your feature request related to a problem? Please describe.**
管理ツールの「スナップショット出力」で出力されるExcelレポートが見づらいため、改善してほしい。
  ・セッションの一覧と、バグ情報が混在しているため、シートを分けたほうがよい
  ・「バグ」しか記載されないため、「気づき」についてもバグとして起票したものは、起票番号含め全量出力してほしい

**Additional context**

**Comment by masaki-tajima** [comment]
現状，Excelには，全てのセッションのバグが出力されます．
これを，セッションごとにシートを分けてほしい，という要望でしょうか？　それ以外の形態でしょうか？
その場合は，セッションが多数になると，シート名にはセッション情報特定のための4カラム（現ExcelのA～D列）が用いられることとなり，シートが多数となった場合の表示が不便になります．
なお，セッションごとのバグ情報であれば，スナップショットのHTMLからもご参照いただけます．

**Comment by masaki-tajima** [comment]
- 対処方針
  - A~G列（テストの目的詳細まで）のシートをもう一つ追加して出力する．
- 背景
今のスナップ出力で出たExcelはテストの目的とバグ＆気づきが1つのシートに出力されている。
これに、A~G列（テストの目的詳細まで）のシートをもう一つ追加して出力してほしい。
理由は、A~G列はスクリプトテストのいわゆるテスト項目表に相当する。
テスト項目表のシートとそれに対するバグ＆気づきの結果表の2シートが出ると、
探索的テストにもかかわらず、スクリプトテストを実施したかのようなテスト項目表＆結果のExcelが出力可能となるため
．
