### ISSUE TITLE
記録の一時停止機能について、記録・管理ツールに明示してほしい

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#587]
**Is your feature request related to a problem? Please describe.**
記録の一時停止機能について、レビュー及びテストスクリプト改修のため、記録・管理ツールの以下箇所への明示を検討いただきたい
①シーケンス図への表示
②テストスクリプトへのコメント文

**Additional context**
既に改修されていたり、他のissueと同様のものがあったらご確認お願いします。

**Comment by fujiwr** [comment]
一時停止した場合、シーケンス図のアクティベーションボックスを分割する。また、分割された新しい方のアクティベーションボックスはクリックされると再開された通番の操作にジャンプできること。
