### ISSUE TITLE
nodejsがインストールされていないとテストスクリプト生成のhtmlドキュメントが作成されない

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#59]
**Describe the bug**
nodejsがインストールされていないとテストスクリプト生成のhtmlドキュメントが作成されない。
※正確にはnodeにパスが通っていない場合。

**To Reproduce**
nodeがインストールされている場合は、事前にpathから除外しておく。

1. 記録ツールで任意のサイトに対して画面遷移、入力操作があるように記録する。
2. テストスクリプト生成を実行する。
3. 出力されたテストスクリプトのzip内に`doc`フォルダが生成されていない。

**Expected behavior**
上記手順で`doc`フォルダおよび配下のhtmlドキュメントが正しく生成されること。

**Comment by masaki-tajima** [comment]
v2.8.0で再現しないためクローズとする．
