### ISSUE TITLE
キャプチャー中特定のページでエラーが発生する

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#61]
**Describe the bug**
下記ページにアクセスし、１回クリックするとエラーが出る

<https://www.amazon.co.jp/%E3%82%AB%E3%82%B9%E3%83%88%E3%83%AD%E3%83%BC%E3%83%AB-%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%82%AA%E3%82%A4%E3%83%AB-POWER1-%E4%BA%8C%E8%BC%AA%E8%BB%8A4%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E7%94%A8%E9%83%A8%E5%88%86%E5%90%88%E6%88%90%E6%B2%B9-Castrol/dp/B001EFHNCI/ref=pd_sbs_3/355-7780928-1706445?pd_rd_w=Y3W5E&pf_rd_p=f9c27313-eebb-475c-8c72-75896fceffe7&pf_rd_r=QYJA62WFPB5JAD3NMVRH&pd_rd_r=982978f7-0073-4d19-b6fa-ea2a141e88c4&pd_rd_wg=X5SSB&pd_rd_i=B001EFHNCI&th=1>

エラーメッセージの一部を下記に抜粋

```
screenElements.$1083.text:
{
  "message": "invalid string value",
  "value": null
}
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
v2.8.0，Chrome111では再現したかったためクローズとする．
