### ISSUE TITLE
記録ツール記録中に「気づきダイアログ」を表示した状態でテスト対象サイトでAlertを開き、気づきを記録すると記録されない

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#62]
記録ツールでバグ、気づきダイアログを表示した後にテスト対象サイトでAlertを開いた場合、スクリーンショット取得ON/OFFが無効化されずエラーメッセージも表示されず、そのままバグ、気づきを記録しようとしても記録されない。
alertを開いた状態でバグ、気づきダイアログを開いた時は正しくエラーメッセージが表示される。

**Comment by masaki-tajima** [comment]
v2.7.1でも再現確認．
