### ISSUE TITLE
ストーリー画面でファイルアップロード時、容量オーバーのエラーメッセージが分かりづらい

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#63]
**Describe the bug**
画面上には不明なエラーと表示され、コンソールには下記メッセージが表示される
Failed to load resource: the server responded with a status of 413 (Payload Too Large)
容量オーバーでアップロードが不可であることを明確に伝えるメッセージを表示できるようにしたい。
- 予め最大容量が決まっているのであれば，その旨も表示（「最大2GBまで」等）

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masaki-tajima** [comment]
「Payload Too Large」の文言から、容量オーバーの旨は理解可能である。
また、2GB以上の大容量ファイルをアップロードすることは運用上考えづらい。
issue整理のためクローズとする。
