### ISSUE TITLE
管理ツールのストーリー画面でテスト実行結果の取り込みを複数回実施すると前回のテスト中の気付きで入力した起票状態、バグ票番号を引き継いでしまう

### ISSUE THREAD

**Issue by s151013** [latteart-org/latteart#7]
**Describe the bug**  
管理ツールのストーリー画面でテスト実行結果の取り込みを複数回実施すると前回のテスト中の気付きで入力した起票状態、バグ票番号を引き継いでしまう

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [v1.7.1]

**Comment by masaki-tajima** [comment]
v2.2.1より起票状態の変更仕様を変更したため，再現せず．Closeとする．
