### ISSUE TITLE
スナップショットでテスト結果のマージを行う

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#767]
バックエンドで画面遷移図や画面部品カバレッジで使用している内部モデルを構築している関係で、サーバが使用できないスナップショットでは動的にテスト結果のマージを行うことができない。
そのため、スナップショット側で実現しようとすると、あらかじめマージ済みのモデルを出力しておくなどが必要となる。
全通りを出そうとすると数が膨大になってしまう可能性があるため、必要なもののみに絞って出力するなどを検討する必要がある。

**Comment by masaki-tajima** [comment]
少なくとも，複数セッションをマージしてレビュー中の画面で表示される画面遷移図・画面要素カバレッジは，静的コンテンツとしてスナップショット出力させたい．

複数セッションをマージしたものを「新たなセッション」として新規保存できるような機能を設け，
ユーザに手動で任意の複数セッションをマージした新セッションを保存させ，そのセッションに対するスナップショットを出力できないか検討したい．

**Comment by fujiwr** [comment]
1つのセッションに複数のテスト結果を紐づけられるようにして対応可能か検討する。
