### ISSUE TITLE
default設定だと画像形式はwebpになっているが、webpでは比較ができないためpngにしたい

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#847]

**Comment by masaki-tajima** [comment]
デフォルトをpngし，設定変更後（png <-> webp変更後）も，LatteArt終了後も維持されて保存されることとする．

**Comment by fujiwr** [comment]
画像圧縮設定

※以下ラジオボタン

- 形式
  - png
  - webp (pngより圧縮率が高まりますが、テスト結果比較機能で画像の比較ができなくなります)

**Comment by fujiwr** [comment]
webp側のファイル名を`xxxxxxx_compressed.webp`ではなく、`xxxxxx.webp`とする。
