### ISSUE TITLE
記録準備が整っていないウィンドウに対する誤操作防止用の暗幕をON/OFFできるようにする

### ISSUE THREAD

**Issue by fujiwr** [latteart-org/latteart#873]

**Comment by fujiwr** [comment]
設定で暗幕をOFFにした場合でも、次回の記録開始時に暗幕を自動的にONにするようにする。

**Comment by masaki-tajima** [comment]
設定画面の項目名を「操作抑止用設定」とします．

「ONにすると、複数のタブ・ウィンドウ・フレームを記録する際、記録対象外のウィンドウの操作を抑止するため、ウィンドウをグレーアウトします。iframe要素内の記録時等、グレーアウトが支障となる場合には一時的にOFFにしてください。（テスト開始時、本設定は自動でONになります。）」
上記文言を設定画面の設定項目を開いたところに記載してください．
