### ISSUE TITLE
記録ツール起動時にブラウザ画面にエラーマークのみが表示され、操作できないケースがある

### ISSUE THREAD

**Issue by ndsuzuki** [latteart-org/latteart#9]
**Describe the bug**
「capture.vbs」を実行し、ブラウザ画面が表示される際、エラーマークのみでコメントがないダイアログが表示され、以後の操作ができない事象が発生する。  
認識している発生条件は以下の通り。  
- latteart-capture-cl、latteart-repositoryの起動完了前にlatteart.exeが実行（起動スクリプトでは各処理は非同期）
- ツールを管理者権限が必要なディレクトリに配置した場合

**Screenshots**
![error](https://user-images.githubusercontent.com/94437032/145970013-270471ba-c2c3-4f84-89f5-ef333b7e6e72.png)

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome v96]
 - Version [1.7.5]

**Comment by masaki-tajima** [comment]
起動スクリプトが改善されたため，本事象は再現しなくなった．クローズとする．
