### ISSUE TITLE
記録ツールで動画を確認するボタンが一度非活性になってしまうと、ダイアログを閉じても活性状態に戻らない

### ISSUE THREAD

**Issue by nemotoaa** [latteart-org/latteart#918]
動画情報が存在しない「open_window」で気づき追加ダイアログを表示し、動画を確認するボタンを押下すると動画が出ないが、ボタンが非活性になり、ダイアログを閉じてもボタンが常に非活性になってしまい、別の操作上で気付きを追加するダイアログを表示して動画を確認しようとしても確認できなくなる。

**Comment by fujiwr** [comment]
#919 の修正により合わせて修正されたためクローズ。
