### ISSUE TITLE
記録開始時に原因不明のエラーで落ちることがある

### ISSUE THREAD

**Issue by mamoru-x-yanagisawa** [latteart-org/latteart#928]

**Comment by masaki-tajima** [comment]
同件か確認いただきたいlogです．
コマンドラインのログと，latteart-capture-clのログをそれぞれ同梱します．

15:08前後：alertの表示
15:10前後：ページ上のテキストを適当にクリック

[logs.zip](https://github.com/latteart-org/latteart/files/12436169/logs.zip)

**Comment by fujiwr** [comment]
> 同件か確認いただきたいlogです．

ログ内の以下2種類のエラーは別issueと同件になります。
- alertのエラー(command_line_1側)
  - #936 と同件
- `timeout while waiting for unlock`エラー(command_line_2側)
  - #929 と同件
